---
- name: add apt keys
  apt_key:
    url: https://downloads.apache.org/cassandra/KEYS
    state: present
  tags: [cassandra]

- name: add apt repository
  apt_repository:
    repo: deb https://downloads.apache.org/cassandra/debian 311x main
    state: present
  tags: [cassandra]

- name: install cassandra
  apt:
    name: cassandra
    state: latest
    update_cache: yes
  notify:
    - stop service
    - empty system directory
    - recreate system directory
    - set no auto bootstrap
  tags: [cassandra]

- meta: flush_handlers
  tags: [cassandra]

- name: render configuration file
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/cassandra.yaml
  notify: restart service
  tags: [cassandra]

- meta: flush_handlers
  tags: [cassandra]

- name: enable service
  service:
    name: cassandra
    enabled: yes
    state: started
  tags: [cassandra]
