---
- name: add ppa repository
  apt_repository:
    repo: ppa:linuxuprising/java
    state: present
  tags: [java]

- name: set license as accepted
  debconf:
    name: oracle-java11-installer
    question: shared/accepted-oracle-license-v1-2
    value: 'true'
    vtype: select
  tags: [java]

- name: install jdk
  apt:
    name: oracle-java11-set-default
    state: latest
    update_cache: yes
  tags: [java]

