---
- name: download binary
  get_url:
    dest: /var/tmp/kafka_2.12-2.1.1.tgz
    url: https://www-eu.apache.org/dist/kafka/2.1.1/kafka_2.12-2.1.1.tgz
  tags: [kafka]

- name: create needed directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /opt/kafka
  tags: [kafka]

- name: unarchive package
  unarchive:
    src: /var/tmp/kafka_2.12-2.1.1.tgz
    dest: /opt/kafka
    remote_src: yes
  tags: [kafka]

- name: render config file
  template:
    src: server.properties.j2
    dest: /etc/kafka.cfg
  tags: [kafka]

- name: render service file
  template:
    src: kafka.service.j2
    dest: /var/tmp/kafka.service
  tags: [kafka]

