---
# Ubuntu Xenial doesn't include Python 2 by default so we have to ensure it is
# installed. Based on: https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: check/perform python2 installation
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: check_python
    changed_when: check_python.stdout != ''

- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - system
    - java

- hosts: zookeeper
  become: yes
  gather_facts: yes
  roles:
    - zookeeper
    - role: systemd
      service_files:
        - /var/tmp/zookeeper.service

- hosts: kafka
  become: yes
  gather_facts: yes
  roles:
    - kafka
    - role: systemd
      service_files:
        - /var/tmp/kafka.service

