---
# - name: update apt repositories
#   apt: update_cache=yes
#   when: add_repository.changed

- name: install MongoDB
  apt:
    name: mongodb
    state: present

- name: render configuration file
  template:
    src: mongodb.conf.j2
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mongodb

- meta: flush_handlers

- name: ensure mongodb is enabled and running
  service:
    name: mongodb
    state: started
    enabled: yes

- name: render replica set init script
  run_once: yes
  template:
    src: initiate.js.j2
    dest: /opt/initiate.js
    mode: 0644
  notify: initiate replica set
  when: '"primary" in group_names'

