---
# - name: update apt repositories
#   apt: update_cache=yes
#   when: add_repository.changed

- name: install MongoDB
  apt:
    name: mongodb
    state: present

- name: render configuration file
  template:
    src: mongodb.conf.j2
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mongodb

- meta: flush_handlers

- name: ensure mongodb is enabled and running
  service:
    name: mongodb
    state: started
    enabled: yes

- name: check configure script
  stat:
    path: /opt/replica_set.js
  register: config_check

- name: choose configure script
  set_fact: configure_script=reconfigure.js.j2
  when: config_check.stat.exists

- name: render replica set config script
  run_once: yes
  template:
    src: '{{ configure_script }}'
    dest: /opt/replica_set.js
    mode: 0644
  notify: configure replica set
  when: '"primary" in group_names'

