# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = {
	node1: { memory: 1024, ip: "172.16.31.101" },
	node2: { memory: 512, ip: "172.16.31.102" },
	node3: { memory: 512, ip: "172.16.31.103" },
	node4: { memory: 512, ip: "172.16.31.104" },
	node5: { memory: 512, ip: "172.16.31.105" },
	node6: { memory: 512, ip: "172.16.31.106" }
}

Vagrant.configure("2") do |config|
	machines.each_with_index do |(hostname, attrs), index|
		config.vm.define hostname do |node|
			node.vm.box = "ubuntu/bionic64"
			node.vm.network "private_network", ip: attrs[:ip]
			node.vm.provider "virtualbox" do |vbox|
				vbox.memory = attrs[:memory]
			end

			if index == machines.size - 1
				config.vm.provision "ansible" do |ansible|
					ansible.limit = "all"
					ansible.playbook = "ansible/site.yml"
					ansible.groups = {
						primary: ["node1"],
						secondary: ["node2", "node3", "node4"],
						arbiter: ["node5"],
						backup: ["node4"],
						example: ["node6"]
					}
				end
			end
		end
	end
end

