# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = "virtualbox"

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network "private_network", ip: "172.24.0.2"
	config.vm.provider "virtualbox"  do |vbox|
		vbox.memory = 1536
	end

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "ansible/site.yml"
		ansible.groups = {
			prometheus: "default"
		}
		ansible.raw_arguments = ENV['ANSIBLE_ARGS']
	end
end

