# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = "virtualbox"

MACHINES = {
	node01: { memory: 1536, ip: "172.24.0.2" },
	node02: { memory: 512, ip: "172.24.0.3" }
}

Vagrant.configure("2") do |config|
	MACHINES.each_with_index do |(hostname, attrs), index|
		config.vm.define hostname do |node|
			node.vm.box = "ubuntu/bionic64"
			node.vm.network "private_network", ip: attrs[:ip]
			node.vm.provider "virtualbox" do |vbox|
				vbox.memory = attrs[:memory]
			end

			if index == MACHINES.size - 1
				config.vm.provision "ansible" do |ansible|
					ansible.limit = "all"
					ansible.playbook = "ansible/site.yml"
					ansible.groups = {
						prometheus: ["node01"],
						examples: ["node02"]
					}
					ansible.raw_arguments = ENV['ANSIBLE_ARGS']
					ansible.extra_vars = {
						examples_target: MACHINES[:node02][:ip] + ":5100"
					}
				end
			end
		end
	end
end

