---
- name: ensure old versions are removed
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent
  tags: [docker]

- name: install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  tags: [docker]

- name: add apt gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [docker]

- name: add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  tags: [docker]

- name: install docker
  apt:
    name: docker-ce
    state: latest
  tags: [docker]

- name: enable non-root users
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  with_items: '{{ non_root_users }}'
  tags: [docker]

