# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = "virtualbox"

MACHINES = {
	node01: { memory: 4096, ip: "172.25.0.2", hostname: "elk-node01" },
	node02: { memory: 512, ip: "172.25.0.3", hostname: "elk-node02" }
}

Vagrant.configure("2") do |config|
	MACHINES.each_with_index do |(hostname, attrs), index|
		config.vm.define hostname do |node|
			node.vm.box = "ubuntu/bionic64"
			node.vm.network "private_network", ip: attrs[:ip]
            node.vm.hostname = attrs[:hostname]
			node.vm.provider "virtualbox" do |vbox|
				vbox.memory = attrs[:memory]
			end

			if index == MACHINES.size - 1
				config.vm.provision "ansible" do |ansible|
					ansible.limit = "all"
					ansible.playbook = "ansible/site.yml"
					ansible.groups = {
						elasticsearch: ["node01"],
                        kibana: ["node01"],
                        # logstash: ["node01"],
						examples: ["node02"]
					}
					ansible.raw_arguments = ENV['ANSIBLE_ARGS']
				end
			end
		end
	end
end

