{
 "title": "Examples",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "zone",
    "query": "label_values(examples_requests_total, zone)"
   }
  ]
 },
 "panels": [
  {
   "title": "Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS / Zone",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (zone) (rate(examples_requests_total{zone=~\"$zone\"}[30s]))",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "RPS / Endpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint) (rate(examples_requests_total{zone=~\"$zone\"}[30s]))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "RPS / Host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (host) (rate(examples_requests_total{zone=~\"$zone\"}[30s]))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Current Rate",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "format": "rps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(examples_requests_total{zone=~\"$zone\"}[30s]))"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (node_memory_MemAvailable_bytes{job=\"examples_vm\"} / node_memory_MemTotal_bytes{job=\"examples_vm\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "(node_memory_Buffers_bytes{job=\"examples_vm\"} + node_memory_Cached_bytes{job=\"examples_vm\"}) / node_memory_MemTotal_bytes{job=\"examples_vm\"}",
       "legendFormat": "Buffers/Cached"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(node_cpu_seconds_total{job=\"examples_vm\", mode=\"idle\"}[1m])",
       "legendFormat": "vCPU {{cpu}}"
      }
     ]
    },
    {
     "title": "Concurrency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"examples\"}",
       "legendFormat": "Goroutines"
      },
      {
       "expr": "go_threads{job=\"examples\"}",
       "legendFormat": "OS Threads"
      }
     ]
    }
   ]
  }
 ]
}