{
 "title": "Prometheus Stack",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{job=\"prometheus_vm\"} / node_memory_MemTotal_bytes{job=\"prometheus_vm\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "(node_memory_Buffers_bytes{job=\"prometheus_vm\"} + node_memory_Cached_bytes{job=\"prometheus_vm\"}) / node_memory_MemTotal_bytes{job=\"prometheus_vm\"}",
     "legendFormat": "Buffers/Cached"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(node_cpu_seconds_total{job=\"prometheus_vm\", mode=\"idle\"}[5m])",
     "legendFormat": "vCPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"prometheus_vm\", mountpoint=~\"/|/data\"} - node_filesystem_avail_bytes{job=\"prometheus_vm\", mountpoint=~\"/|/data\"})\n/ (node_filesystem_size_bytes{job=\"prometheus_vm\", mountpoint=~\"/|/data\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Services Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"grafana\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus_vm\"}",
     "legendFormat": "Node Exporter"
    }
   ]
  }
 ]
}